apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       docker
        Tag          kube.*
        Refresh_Interval 5
        Skip_Long_Lines On

    [FILTER]
        Name         grep
        Match        kube.*
        Regex        container_name iot-app

    [OUTPUT]
        Name         file
        Match        *
        Path         /var/log
        File         iot-app.log
        Format       plain
