apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-app
  template:
    metadata:
      labels:
        app: iot-app
    spec:
      containers:
        - name: iot-app
          image: public.ecr.aws/q1n7m0l5/iot-app:v0.0.2
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: iot-app
spec:
  selector:
    app: iot-app
  ports:
    - port: 80
      targetPort: 8080
