apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 22.0.4 # pin a version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: bitnami/redis
      tag: 8.2.1-debian-12-r0
      arch: arm64
    auth:
      enabled: false # disable password for simplicity (not for prod!)
