apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-app
  template:
    metadata:
      labels:
        app: iot-app
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: iot-app
          image: 914165346309.dkr.ecr.us-east-1.amazonaws.com/iot-app:v0.0.7
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PORT
              value: "6379"
